# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
osx_image: xcode7

env:
    global:
        - UPLOAD_IOS_SNAPSHOT_BUCKET_NAME=uibuttons-snapshots
        - secure: "bhCQbsey4xZhoqirOtKV/H2X2C9bR3YDH+NfRCQeEM5lgq+mk7EB9QmeE6Io+Fb6T2lKSEjnU8u+QV82Fuy358Z/RgeUcz9FZXA3oJR8TNUwdBU9OwL3q1vBrSXg2QqUtdld2ab3BDjzE7+Ja45PgsqrDX/8MkHQJTAy1/Fp3mk="
        - secure: "Wj72iTvNTKkYpwjMeTe4rQ6u4xY+SVwAmjFD/pqIjW5BET4Cq6LP4Rt0VgtVO11B6tCktVE0VdnhS1zs+ljCCaEes7yVJziYTKgwNd/PY9Ll0F2AZsJ64fxTr6caRI/GUhq+dYPGASO3S716+muiN6eqwRgWWUWPpTy6urtPMbk="

install:
        - bundle install --without development --deployment --jobs=3 --retry=3
        - bundle exec pod repo update --silent
        - bundle exec pod install --project-directory=Example

cache:
        directories:
                - vendor/bundle
                - Example/Pods

before_script:
    - export LANG=en_US.UTF-8
    - make ci

script:
    - make test
